# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controladora.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
import serial 
from PyQt5 import QtCore, QtGui, QtWidgets
puertoSerial = serial.Serial('COM4', 9600,timeout=1)
#Retardo para establecer la conexión serial
time.sleep(1.8) 

puertoSerial.write(str.encode('a'))
time.sleep(1)
class Ui_ControladoraDeVentiladores(object):
    def setupUi(self, ControladoraDeVentiladores):
        ControladoraDeVentiladores.setObjectName("ControladoraDeVentiladores")
        ControladoraDeVentiladores.resize(241, 320)
        self.controladoraDeVentilacionEIluminacion = QtWidgets.QWidget(ControladoraDeVentiladores)
        self.controladoraDeVentilacionEIluminacion.setStyleSheet("*{\n"
"family-found: century gothic;\n"
"}\n"
"QWidget{\n"
"background-image: url(:/images/images/bg.jpg);\n"
"}\n"
"QFrame#contenedor{\n"
"background:#252853;\n"
"}\n"
"QLabel#titulo{\n"
"color:white;\n"
"background:#252853;\n"
"font-size:18px;\n"
"}\n"
"QLabel#titulo_2{\n"
"color:white;\n"
"background:#252853;\n"
"font-size:18px;\n"
"}\n"
"QLabel#v2{\n"
"color:white;\n"
"background:#252853;\n"
"font-size:12px;\n"
"}\n"
"QLabel#v1{\n"
"color:white;\n"
"background:#252853;\n"
"font-size:12px;\n"
"}\n"
"QLabel#velocidad{\n"
"color:#E5BE01;\n"
"background:#252853;\n"
"font-size:14px;\n"
"}\n"
"QRadioButton{\n"
"color:white;\n"
"background:#252853;\n"
"font-size:12px;\n"
"}\n"
"QLabel#iluminacion{\n"
"color:#E5BE01;\n"
"background:#252853;\n"
"font-size:14px;\n"
"}\n"
"\n"
"QLabel#nombre{\n"
"color:white;\n"
"\n"
"font-size:10px;\n"
"}\n"
"QPushButton#aplicar{\n"
"font-size:16px;\n"
"background:white;\n"
"}")
        self.controladoraDeVentilacionEIluminacion.setObjectName("controladoraDeVentilacionEIluminacion")
        self.contenedor = QtWidgets.QFrame(self.controladoraDeVentilacionEIluminacion)
        self.contenedor.setGeometry(QtCore.QRect(10, 20, 221, 291))
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.titulo = QtWidgets.QLabel(self.contenedor)
        self.titulo.setGeometry(QtCore.QRect(20, 10, 181, 31))
        self.titulo.setObjectName("titulo")
        self.titulo_2 = QtWidgets.QLabel(self.contenedor)
        self.titulo_2.setGeometry(QtCore.QRect(50, 40, 131, 20))
        self.titulo_2.setObjectName("titulo_2")
        self.v1 = QtWidgets.QLabel(self.contenedor)
        self.v1.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.v1.setObjectName("v1")
        self.v2 = QtWidgets.QLabel(self.contenedor)
        self.v2.setGeometry(QtCore.QRect(110, 80, 71, 16))
        self.v2.setObjectName("v2")
        self.velocidad = QtWidgets.QLabel(self.contenedor)
        self.velocidad.setGeometry(QtCore.QRect(20, 100, 61, 16))
        self.velocidad.setObjectName("velocidad")
        self.iluminacion = QtWidgets.QLabel(self.contenedor)
        self.iluminacion.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.iluminacion.setObjectName("iluminacion")
        self.comboBox = QtWidgets.QComboBox(self.contenedor)
        self.comboBox.setGeometry(QtCore.QRect(30, 130, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.contenedor)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 130, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.contenedor)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 200, 81, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.contenedor)
        self.comboBox_4.setGeometry(QtCore.QRect(130, 200, 81, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.aplicar = QtWidgets.QPushButton(self.contenedor)
        self.aplicar.setGeometry(QtCore.QRect(80, 250, 75, 23))
        self.aplicar.setObjectName("aplicar")
        self.nombre = QtWidgets.QLabel(self.controladoraDeVentilacionEIluminacion)
        self.nombre.setGeometry(QtCore.QRect(10, 0, 171, 16))
        self.nombre.setObjectName("nombre")
        ControladoraDeVentiladores.setCentralWidget(self.controladoraDeVentilacionEIluminacion)
        
        self.aplicar.clicked.connect(self.sending)
        
        self.retranslateUi(ControladoraDeVentiladores)
        QtCore.QMetaObject.connectSlotsByName(ControladoraDeVentiladores)

    def retranslateUi(self, ControladoraDeVentiladores):
        _translate = QtCore.QCoreApplication.translate
        ControladoraDeVentiladores.setWindowTitle(_translate("ControladoraDeVentiladores", "MainWindow"))
        self.titulo.setText(_translate("ControladoraDeVentiladores", " Control de ventilación"))
        self.titulo_2.setText(_translate("ControladoraDeVentiladores", "con iluminación"))
        self.v1.setText(_translate("ControladoraDeVentiladores", "Ventilador 1"))
        self.v2.setText(_translate("ControladoraDeVentiladores", "Ventilador 2"))
        self.velocidad.setText(_translate("ControladoraDeVentiladores", "Velocidad"))
        self.iluminacion.setText(_translate("ControladoraDeVentiladores", "Iluminación"))
        self.comboBox.setItemText(0, _translate("ControladoraDeVentiladores", "ALTA"))
        self.comboBox.setItemText(1, _translate("ControladoraDeVentiladores", "MEDIA"))
        self.comboBox.setItemText(2, _translate("ControladoraDeVentiladores", "BAJA"))
        self.comboBox_2.setItemText(0, _translate("ControladoraDeVentiladores", "ALTA"))
        self.comboBox_2.setItemText(1, _translate("ControladoraDeVentiladores", "MEDIA"))
        self.comboBox_2.setItemText(2, _translate("ControladoraDeVentiladores", "BAJA"))
        self.comboBox_3.setItemText(0, _translate("ControladoraDeVentiladores", "Secuencia 1"))
        self.comboBox_3.setItemText(1, _translate("ControladoraDeVentiladores", "Secuencia 2"))
        self.comboBox_3.setItemText(2, _translate("ControladoraDeVentiladores", "Secuencia 3"))
        self.comboBox_3.setItemText(3, _translate("ControladoraDeVentiladores", "Secuencia 4"))
        self.comboBox_4.setItemText(0, _translate("ControladoraDeVentiladores", "Secuencia 1"))
        self.comboBox_4.setItemText(1, _translate("ControladoraDeVentiladores", "Secuencia 2"))
        self.comboBox_4.setItemText(2, _translate("ControladoraDeVentiladores", "Secuencia 3"))
        self.comboBox_4.setItemText(3, _translate("ControladoraDeVentiladores", "Secuencia 4"))
        self.aplicar.setText(_translate("ControladoraDeVentiladores", "Aplicar"))
        self.nombre.setText(_translate("ControladoraDeVentiladores", "Camargo Hernández Alan Mauricio"))
    def sending(self):
      v1=self.comboBox.currentText()
      v2=self.comboBox_2.currentText()
      led1=self.comboBox_3.currentText()
      led2=self.comboBox_4.currentText()
      if v1=='ALTA' and v2=='ALTA':
        codigo='a'
      elif v1=='ALTA' and v2=='MEDIA':
        codigo='b'
      elif v1=='ALTA' and v2=='BAJA':
        codigo='c'
      elif v1=='MEDIA' and v2=='ALTA':
        codigo='d'
      elif v1=='MEDIA' and v2=='MEDIA':
        codigo='e'
      elif v1=='MEDIA' and v2=='BAJA':
        codigo='f'
      elif v1=='BAJA' and v2=='ALTA':
        codigo='g'
      elif v1=='BAJA' and v2=='MEDIA':
        codigo='h'
      elif v1=='BAJA' and v2=='BAJA':
        codigo='i'
      puertoSerial.write(str.encode(codigo))
      print(codigo)
      time.sleep(3)
      #-----------------------------------
      if led1=='Secuencia 1':
        codigo='j'
      elif led1=='Secuencia 2':
        codigo='k'
      elif led1=='Secuencia 3':
        codigo='l'
      elif led1=='Secuencia 4':
        codigo='m'
      puertoSerial.write(str.encode(codigo))
      print(codigo)
      time.sleep(3)
      #-----------------------------------
      if led2=='Secuencia 1':
        codigo='n'
      elif led2=='Secuencia 2':
        codigo='o'
      elif led2=='Secuencia 3':
        codigo='p'
      elif led2=='Secuencia 4':
        codigo='q'
      puertoSerial.write(str.encode(codigo))
      print(codigo)
      time.sleep(3)
import source5

if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    ControladoraDeVentiladores = QtWidgets.QMainWindow()
    ui = Ui_ControladoraDeVentiladores()
    ui.setupUi(ControladoraDeVentiladores)
    ControladoraDeVentiladores.show()
    sys.exit(app.exec_())

puertoSerial.close()
